### ISSUE TITLE
Got "pipe: Invalid argument" every time whenever http-gettter is ran

### ISSUE THREAD

**Issue by zzzuzik** [tohojo/http-getter#1]
HI @tohojo,

Thank you for the netperf-wrapper!
I'm trying to make the http-getter running alongside accordingly to the docs.
However, every time if bails out with `pipe: Invalid argument` no logs in the output file
filelist.txt is accessible over HTTP. its content:

```
http://<IP>/file1
http://<IP>/file2
http://<IP>/file3
```

Linux: CentOS 6.6

Appreciate your help.

**Comment by tohojo** [comment]
> Linux: CentOS 6.6

Hmm, it seems the O_DIRECT flag to pipe() only works for Linux 3.4 or
newer. This is used for the internal communication between the main
http-getter process and the worker processes.

Since this flag is Linux-only in any case, I was planning to get rid of
it in any case, but that requires restructuring the code a little bit.
I'll see if I can get around to that soonish...

**Comment by zzzuzik** [comment]
I can confirm that it was fixed. Thank you @tohojo for the prompt fix.
Cheers!
